# this is the fake postgresql-secrets.yml, don't steal my db info ;)
# thanks for the help chatGPT, I asked: for the postgresql-secrets.yml I want to make, is there a way to redo this with the sqlalchemy convention..." with the old line from the twogeCICD project as well as the commented out secrets file from goldenwaste
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  # well why doesn't secrets need a label?  
type: Opaque
# will this data really work? chatGPT stuck the entire "postgresql://<user>:<password>@localhost/twoge_db" into <string>: echo -n <string> | base64. I may need to separate user, db, root user, password?
# stack overflow says to use stringData maybe: https://stackoverflow.com/questions/73680884/kubernetes-cannot-be-handled-as-a-secret-illegal-base64-data-when-using-environm
#stringData:
data:
  # from Chandra same day in Slack: URI Format - <database_engine>://<username>:<password>@<host>:<port>/<database_name> 
  #sqlalchemy_db_uri: <database_engine>://<username>:<password>@<host>:<port>/<database_name> 
  twoge-db: dbbase64
  username: userbase64
  password: passbase64