# from CP Alpha DevOps curriculum
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: "twoge-ns"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi