apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: matthawkiit/my-app-image:latest    # image from dockerhub, ask chatGPT how to do it with an image "pushed" to minikube instead of dockerhub sometime
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
