# I would normally put this file in .gitignore but it is just a basic example
# had to write this, chatGPT forgot
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: bXlwYXNzd29yZA==
  username: bXl1c2Vy
